Controllers/DepositController.cs
using Microsoft.AspNetCore.Mvc;
using MvcMCBA.Data;
using MvcMCBA.Models;

namespace MvcMCBA.Controllers
{
    public class DepositController : Controller
    {
        private readonly MvcMCBAContext _context;

        public DepositController(MvcMCBAContext context) => _context = context;

        public IActionResult Index()
        {
            var customerID = HttpContext.Session.GetInt32("CustomerID");

            if (customerID == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var accounts = _context.Account.Where(a => a.CustomerID == customerID).ToList();
            var customer = _context.Customer
                .Where(c => c.CustomerID == customerID)
                .FirstOrDefault();
            ViewBag.Accounts = accounts;
            ViewBag.CustomerName = customer.Name;

            return View(new Transaction());
        }

        [HttpPost]
        public async Task<IActionResult> Index(Transaction transaction)
        {

            if (!ModelState.IsValid)
            {
                var customerID = HttpContext.Session.GetInt32("CustomerID");
                var accounts = _context.Account.Where(a => a.CustomerID == customerID).ToList();
                ViewBag.Accounts = accounts;

                return View(transaction);
            }

            transaction.TransactionType = "D";
            transaction.TransactionTimeUtc = DateTime.UtcNow;
            transaction.Account = await _context.Account.FindAsync(transaction.AccountNumber);

            _context.Transaction.Add(transaction);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Accounts");
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using MvcMCBA.Data;
using SimpleHashing.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;


namespace MvcMCBA.Controllers
{

    [AllowAnonymous]
    public class LoginController : Controller
    {
        private readonly MvcMCBAContext _context;

        public LoginController(MvcMCBAContext context) => _context = context;

        public IActionResult Index() => View();

        [HttpPost]
        public async Task<IActionResult> Index(string loginID, string password)
        {
            if (string.IsNullOrEmpty(password))
            {
                ModelState.AddModelError(nameof(password), "Password is Required");
                return View();
            }

            var loggedInUser = await _context.Login.FirstOrDefaultAsync(x => x.LoginID == loginID);

            if (loggedInUser == null || password == null || !new SimpleHash().Verify(password, loggedInUser.PasswordHash))
            {
                ModelState.AddModelError(string.Empty, "Invalid Login ID or Password");
                return View();
            }
            HttpContext.Session.SetInt32("CustomerID", loggedInUser.CustomerID);

            return RedirectToAction("Index", "Accounts");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using MvcMCBA.Data;
using MvcMCBA.Models;
using Microsoft.EntityFrameworkCore;

namespace MvcMCBA.Controllers
{
    public class ProfileController : Controller
    {
        private readonly MvcMCBAContext _context;

        public ProfileController(MvcMCBAContext context) => _context = context;

        public async Task<IActionResult> Index()
        {
            var customerID = HttpContext.Session.GetInt32("CustomerID");

            if (customerID == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var customer = await _context.Customer
                .FirstOrDefaultAsync(c => c.CustomerID == customerID);

            return View(customer);
        }

        public async Task<IActionResult> Edit()
        {
            var customerID = HttpContext.Session.GetInt32("CustomerID");

            var customer = await _context.Customer
                .FirstOrDefaultAsync(c => c.CustomerID == customerID);

            return View(customer);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Customer customer)
        {
            if (!ModelState.IsValid)
            {
                return View(customer);
            }

            var customerFromDb = await _context.Customer
                .Include(c => c.Accounts) 
                .Include(c => c.Login)  
                .FirstOrDefaultAsync(c => c.CustomerID == customer.CustomerID);

            customerFromDb.Name = customer.Name;
            customerFromDb.TFN = customer.TFN;
            customerFromDb.Address = customer.Address;
            customerFromDb.City = customer.City;
            customerFromDb.State = customer.State;
            customerFromDb.Postcode = customer.Postcode;
            customerFromDb.Mobile = customer.Mobile;

                customerFromDb.Accounts = customer.Accounts;
                customerFromDb.Login = customer.Login;

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Controllers/TransferController.cs
using Microsoft.AspNetCore.Mvc;
using MvcMCBA.Data;
using MvcMCBA.Models;
using Microsoft.EntityFrameworkCore;

namespace MvcMCBA.Controllers
{
    public class TransferController : Controller
    {
        private readonly MvcMCBAContext _context;
        public TransferController(MvcMCBAContext context) => _context = context;

        public IActionResult Index()
        {
            var customerID = HttpContext.Session.GetInt32("CustomerID");

            if (customerID == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var accounts = _context.Account.Where(a => a.CustomerID == customerID).ToList();
            var customer = _context.Customer
                .Where(c => c.CustomerID == customerID)
                .FirstOrDefault();
            ViewBag.Accounts = accounts;
            ViewBag.CustomerName = customer.Name;

            return View(new Transaction());
        }
        [HttpPost]
        public async Task<IActionResult> Index(Transaction transaction)
        {
            if (transaction.AccountNumber == transaction.DestinationAccountNumber)
            {
                ModelState.AddModelError(nameof(transaction.DestinationAccountNumber), "You cannot transfer to the same account");
            }

            if (transaction.DestinationAccountNumber == null)
            {
                ModelState.AddModelError(nameof(transaction.DestinationAccountNumber), "Destination Account is required");
            }

            var transferAccount = await _context.Account.FindAsync(transaction.DestinationAccountNumber);

            if (transferAccount == null)
            {
                ModelState.AddModelError(nameof(transaction.DestinationAccountNumber), "Destination Account not found");
            }

            var balance = await _context.Transaction
               .Where(t => t.AccountNumber == transaction.AccountNumber)
               .SumAsync(t => t.Amount);

            if (balance < transaction.Amount)
            {
                ModelState.AddModelError(nameof(transaction.Amount), "Insufficient funds.");
            }

            if (!ModelState.IsValid)
            {
                var customerID = HttpContext.Session.GetInt32("CustomerID");
                var accounts = _context.Account.Where(a => a.CustomerID == customerID).ToList();
                ViewBag.Accounts = accounts;
                return View(transaction);
            }

            transaction.TransactionType = "T";
            transaction.TransactionTimeUtc = DateTime.UtcNow;

            var transferFrom = new Transaction
            {
                TransactionType = "T",
                AccountNumber = transaction.AccountNumber,
                DestinationAccountNumber = transaction.DestinationAccountNumber,
                Amount = -transaction.Amount,
                Comment = transaction.Comment,
                TransactionTimeUtc = transaction.TransactionTimeUtc,
                Account = await _context.Account.FindAsync(transaction.AccountNumber),
                DestinationAccount = transferAccount
            };

            _context.Transaction.Add(transferFrom);

            var transferTo = new Transaction
            {
                TransactionType = "T",
                AccountNumber = (int)transaction.DestinationAccountNumber,
                Amount = transaction.Amount,
                Comment = transaction.Comment,
                TransactionTimeUtc = transaction.TransactionTimeUtc,
                Account = transferAccount,
                DestinationAccount = await _context.Account.FindAsync(transaction.AccountNumber)
            };

            _context.Transaction.Add(transferTo);

            var serviceFee = new Transaction
            {
                TransactionType = "S",
                AccountNumber = transaction.AccountNumber,
                Amount = -0.10m,
                Comment = "Transfer Fee",
                TransactionTimeUtc = transaction.TransactionTimeUtc,
                Account = await _context.Account.FindAsync(transaction.AccountNumber)
            };

            _context.Transaction.Add(serviceFee);

            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Accounts");
        }

    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MCBA App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">MCBA</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-nav flex-grow-1">
                    <ul class="navbar-nav">
                        @{
                            var isLoggedIn = Context.Session.GetInt32(nameof(Customer.CustomerID)).HasValue;
                        }
                        @if (isLoggedIn)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Accounts" asp-action="Index">Accounts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Deposit" asp-action="Index">Deposit</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Withdraw" asp-action="Index">Withdraw</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Transfer" asp-action="Index">Transfer</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Statements" asp-action="Index">My Statements</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Profile" asp-action="Index">My Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MCBA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>